### PR TITLE
account for missing creationDate on readDir response

### PR DESCRIPTION
**Pull request by notsolucky**
The library threw an error when trying to get directory content details from a Nextcloud server.
The reason was that the server response did not include the creationdate property in the result.
This will check for the presence of that property before trying to access it.

### CODE REVIEW

**Comment by floriansimon1** [comment]
Any update, @AdrienCastex?

**Comment by kevinley** [comment]
Hello, @AdrienCastex can we merge this ?

**Comment by dgtlmoon** [comment]
@AdrienCastex would be great to see this one in! I'm working on some integration also

**Comment by AdrienCastex** [comment]
Hello,

Very great job!
Sorry for the merge delay.

Thank you very much for your contribution.

**Pull request merged**
